apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80            # The port on which the service will listen
      targetPort: 80      # The port to which traffic will be forwarded to
