
+-------------+--------------------------------------------------------+
| Instruction |                      Description                       |
+-------------+--------------------------------------------------------+
| ADD         | Add local or remote files and directories.             |
| ARG         | Use build-time variables.                              |
| CMD         | Specify default commands.                              |
| COPY        | Copy files and directories.                            |
| ENTRYPOINT  | Specify default executable.                            |
| ENV         | Set environment variables.                             |
| EXPOSE      | Describe which ports your application is listening on. |
| FROM        | Create a new build stage from a base image.            |
| RUN         | Execute build commands.                                |
| USER        | Set user and group ID.                                 |
| VOLUME      | Create volume mounts.                                  |
| WORKDIR     | Change working directory.                              |
+-------------+--------------------------------------------------------+

